# URL에 세션 남기는거 방지 server.servlet.session.tracking-modes=cookie
# 1800초(30분) 후에 세션 종료  server.servlet.session.timeout=1800
#Datasource Configuration
spring:
  profiles:
    include:
      oauth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cco3y08h29y1.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: root
    password: rootroot
  # JP
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: db4d03b4724f561919c3f1e9e4ed8425
            client-secret: YnvMeUZEI4rgHUgtsdKfm3HZ6Zd3Y5Df
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  sql:
    init:
      platform: postgres
